// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWtQhkKoGa2AUb3k9QBik7AJAI_LdcR68',
    appId: '1:1062880928349:web:037f4d4d82e87b0f82e3b4',
    messagingSenderId: '1062880928349',
    projectId: 'zarity-6124d',
    authDomain: 'zarity-6124d.firebaseapp.com',
    storageBucket: 'zarity-6124d.appspot.com',
    measurementId: 'G-VSY4WCCBC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZXO4sX0lCMR4uUQGd2oTkM7twTkCTGMg',
    appId: '1:1062880928349:android:7d7ccf924cb3e0a482e3b4',
    messagingSenderId: '1062880928349',
    projectId: 'zarity-6124d',
    storageBucket: 'zarity-6124d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApJXXSUObVEpyb9EOtHheKMpVHGWDQW8g',
    appId: '1:1062880928349:ios:cb24d94b62051d0b82e3b4',
    messagingSenderId: '1062880928349',
    projectId: 'zarity-6124d',
    storageBucket: 'zarity-6124d.appspot.com',
    iosClientId: '1062880928349-i9t8b7pprv44s0b010m8van4tbvu9kot.apps.googleusercontent.com',
    iosBundleId: 'com.example.zarityInternAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApJXXSUObVEpyb9EOtHheKMpVHGWDQW8g',
    appId: '1:1062880928349:ios:cb24d94b62051d0b82e3b4',
    messagingSenderId: '1062880928349',
    projectId: 'zarity-6124d',
    storageBucket: 'zarity-6124d.appspot.com',
    iosClientId: '1062880928349-i9t8b7pprv44s0b010m8van4tbvu9kot.apps.googleusercontent.com',
    iosBundleId: 'com.example.zarityInternAssignment',
  );
}
